package com.cmcguire;// Generated by Selenium IDE
import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class ViewSingletonProfilesTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void viewSingletonProfiles() {
    driver.get("http://localhost:8080/");
    driver.manage().window().setSize(new Dimension(695, 728));
    driver.findElement(By.linkText("Add a Profile")).click();
    driver.findElement(By.id("userName")).click();
    driver.findElement(By.id("userName")).sendKeys("Elizabeth Bennet");
    driver.findElement(By.id("email")).click();
    driver.findElement(By.id("email")).sendKeys("e.bennet@longbourn.ac.uk");
    driver.findElement(By.id("location")).click();
    driver.findElement(By.id("location")).sendKeys("Meryton");
    driver.findElement(By.cssSelector(".btn")).click();
    {
      List<WebElement> elements = driver.findElements(By.id("singleton-list"));
      assert(elements.size() > 0);
    }
  }
}
